###PRODUCT SVC CONFIGMAP
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-grpc-order-svc-config
data:
  PORT: :50052
  DB_URL: postgres://postgres:password@postgres-order:5432/order_svc
  JWT_SECRET_KEY: r43t18sc
---
###order SVC DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-grpc-order-svc
  labels:
    app_name: go-grpc-project
    app: go-grpc-order-svc
    tier: svc
spec:
  selector:
    matchLabels:
      app: go-grpc-order-svc
      tier: svc
  template:
    metadata:
      labels:
        app: go-grpc-order-svc
        tier: svc
    spec:
      initContainers:
        - name: init-wait-for-db
          image: alpine
          command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 postgres-order 5432 && exit 0 || sleep 3; done; exit 1"]
        - name: wait-go-grpc-product-svc
          image: alpine
          command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 go-grpc-product-svc 50052 && exit 0 || sleep 3; done; exit 1"]
      containers:
      - name: go-grpc-order-svc
        image: utils-go-grpc-order-svc
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50053
        env:
            - name: ENVRIONMENT
              value: K8S
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: go-grpc-order-svc-config
                  key: PORT
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: go-grpc-order-svc-config
                  key: DB_URL
            - name: PRODUCT_SVC_URL
              value: go-grpc-product-svc:50052      
---
###order SVC SERVICE
apiVersion: v1
kind: Service
metadata:
  name: go-grpc-order-svc
spec:
  selector:
    app: go-grpc-order-svc
    tier: svc
  ports:
    - port: 50053
      targetPort: 50053
      name: order-svc
      protocol: TCP